<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE appconfig [
        <!ELEMENT appconfig (rmi, datasource)>
        <!ELEMENT rmi (server, client, classprovider?)>
        <!ELEMENT server ((registry, bindedobject*)+)>
        <!ELEMENT registry (createregistry, registryaddress, registryPort)>
        <!ELEMENT client (policypath, usecodebaseonly)>
        <!ELEMENT createregistry (#PCDATA)> <!-- valid values: “yes”, “no” -->
        <!ELEMENT registryaddress (#PCDATA)> <!-- valid IP X.X.X.X (X=>0-255)
or valid host name -->
        <!ELEMENT registryPort (#PCDATA)>
        <!ELEMENT bindedobject EMPTY>
        <!ELEMENT policypath (#PCDATA)>
        <!-- FS depended path (absolute or relative) to *.policy file -->
        <!ELEMENT usecodebaseonly (#PCDATA)> <!-- valid values: “yes”, “no” -->
        <!ELEMENT classprovider (#PCDATA)> <!-- valid FS depended path to local
directory or *jar file, or URL to *.jar file, containing *.class files -->
        <!ELEMENT datasource (classname, drivertype, hostName, port, DBName,
                user, pass)>
        <!ELEMENT classname (#PCDATA)>
        <!ELEMENT drivertype (#PCDATA)>
        <!ELEMENT hostName (#PCDATA)>
        <!ELEMENT port (#PCDATA)>
        <!ELEMENT DBName (#PCDATA)>
        <!ELEMENT user (#PCDATA)>
        <!ELEMENT pass (#PCDATA)>
        <!ATTLIST bindedobject
                name CDATA #REQUIRED
                class CDATA #REQUIRED
                >
        ]>
<appconfig>
    <rmi>
        <server>
            <registry>
                <createregistry>yes</createregistry>
                <registryaddress>localhost</registryaddress>
                <registryPort>1099</registryPort>
            </registry>
        </server>
        <client>
            <policypath>client.policy</policypath>
            <usecodebaseonly>no</usecodebaseonly>
        </client>
        <classprovider>http://www.yourhost.free.ru/cp/cp.jar</classprovider>
    </rmi>
    <datasource>
        <classname>com.mysql.jdbc.jdbc2.optional.MysqlDataSource</classname>
        <drivertype></drivertype>
        <hostName>localhost</hostName>
        <port>3306</port>
        <DBName>housekeeper</DBName>
        <user>admin</user>
        <pass>admin</pass>
    </datasource>
</appconfig>